# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: 'Research Repository Documentation'

repo_url: https://github.com/acd-research-repo/research-repository

theme:
    name: material
    icon:
        logo: material/book-open-variant
    language: en

    palette:
        - media: '(prefers-color-scheme: dark)'
          scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/weather-night
              name: Switch to light mode

    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - navigation.expand

        - navigation.path
        - navigation.sections

        - content.code.copy
        - content.code.annotate

        - search.share
        - search.suggest
        - search.highlight

        - toc.follow

extra:
    generator: false

nav:
    - Home: index.md
    - Specification: specification.md
    - API Contract: api_contract.md
    - Database: database_migration.md
    - Testing: testing.md
    - Contribute: contribute.md
    - Plans: future_plans.md

extra_javascript:
    - js/open_in_new_tab.js
    - js/stats.js

markdown_extensions:
    - pymdownx.tasklist:
          custom_checkbox: true
          clickable_checkbox: false

    - toc:
          permalink: true

    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true

    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
